workflow: build: Add scheduled runs for builds
Corigine/nfp-drv-kmods pull request #15
Opened 2024-01-10 09:51 UTC by dano-corigine

Adds a scheduled run to test and verify the build for the series of commits that were merged to main within the week. This way issues can be escalated faster.

2024-01-10 09:55 UTC, dano-corigine commented
CC: @AnnemiePotgieter for CI visibility

2024-01-10 14:39 UTC, cmurcott-corigine approved these changes
This seems good to me, given the context of the problem. I suppose you could look at running the workflow more frequently, but weekly could be ok depending on the expected frequency of the upstream changes.

You are welcome to add my ACK -
```
Acked-by: Charles Murcott <charles.murcott@corigine.com>
```

2024-01-10 15:31 UTC, louis-peens requested changes
Thanks for working on this Dano. Please create this against the `public-main` branch of `nfp-drv-kmods-private`.

I think daily is probably better (though weekly is already a lot better than the nothing we currently have). It is using github runners, so wouldn't interfere with our local runners.

2024-01-11 07:50 UTC, dano-corigine commented
Moving over

2024-01-11 07:50 UTC, closed without merging